import Head from 'next/head'
import PostCard from './components/PostCard'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="bg-slate-900 h-screen w-screen grid gap-8 grid-cols-6 font-Outfit">
        {/* / */}
        <div className="pr-18 ">
          {/* <Sidebar /> */}
        </div>

        <div className="col-span-3 col-span-2 px-18 pt-14">
          <PostCard />
        </div>


        <div className="col-span-2 adv bg-slate h-screen"></div>



      </div>
      </main>
    </>
  )
}
