import Head from 'next/head'
import PostCard from '../components/PostCard1'
import Navbar from '@/components/Navbar'
// import Advertise from '@/components/Advertise'
import NewPost from '@/components/NewPost'
import { contractAddress } from '../../backend/config'
import abi from '../../backend/artifacts/contracts/Socialchain.sol/Socialchain.json'
import { useEffect, useState } from 'react'
import Web3Modal from 'web3modal'
import {ethers} from 'ethers'



export default function Home() {

  const [messages, setMessages] = useState([]);


  useEffect(() => {
    console.log(contractAddress)
  }, [])

  async function getMessages() {
    try {
      const web3Modal = new Web3Modal()
      const connection = await web3Modal.connect()
      const provider = new ethers.providers.Web3Provider(connection)
      const signer = provider.getSigner()
      const contract = new ethers.Contract(
        contractAddress,
        abi.abi,
        signer
      )

      const msgList = await contract.getPost()
      let messagesClean = [];
      msgList.forEach((message) => {
        messagesClean.push({
          id: message.id.toString(),
          content: message.content,
          likes: message.likes.toNumber(),
          dislikes: message.dislikes.toNumber(),
          imageurl: message.image,
          username: message.account.username,
        })
      })

      setMessages(messagesClean);
      console.log(messagesClean);

    } catch (e) {
      console.log(e);
    }

  }

  useEffect(() => {
    getMessages()
  }, [])


  return (
    <>
      <Head>
        <title>sociochain </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./logo.png" />
      </Head>
      <main>
        {/* NavBar */}
        <div className='w-full '>
          <Navbar />
        </div>
        <div className="p-4 lg:ml-64 dark:bg-gray-950">
          {/* Body */}
          <div className="pt-20 bg-rounded-lg ">
            <div className="grid lg:grid-cols-5 gap-4 mb-4">
              <div className='col-span-4 sm:col-span-3 '>
                <PostCard />
                <PostCard />
                <PostCard />
                <PostCard />
                <PostCard />
                <PostCard />
              </div>
              <div className=" hidden sticky lg:block xl:col-span-2 pr-3">

                <NewPost />

              </div>
              {/* <Advertise /> */}
            </div>
          </div>
        </div>
      </main >
    </>
  )
}
